schema = {
    "insertion_sort": ["input", "output"],
    "bubble_sort": ["input", "output"],
    "heap_sort": ["input", "output"],
    "quick_sort": ["input", "output"],
    "minimum": ["input", "output"],
    "binary_search": ["input", "output", "target"],
    "quick_select": ["input", "output"],
    "maximum_subarray": ["input", "start", "end"],
    "activity_selection": ["input_f", "input_s", "output"],
    "task_scheduling": ["input_d", "input_w", "output"],
    "matrix_chain_mul": ["input", "output"],
    "longest_common_subseq": ["input_d", "input_string", "output", "output_arrows"],
    "opt_bst": ["input_p", "input_q", "output"],
    "bfs": ["input", "start", "output"],
    "dfs": ["input", "output"],
    "topological_sort": ["input", "output_head", "output"],
    "articulation_points": ["input", "output"],
    "strongly_connected_comps": ["input", "output"],
    "kruskal": ["input", "output"],
    "prim": ["input", "start", "output"],
    "bellman_ford": ["input", "start", "output"],
    "dijkstras": ["input", "start", "output"],
    "floyd_warshall": ["input", "output"],
    "DAG_sp": ["input", "start", "output"],
    "naive_strings": ["input", "string", "output"],
    "kmp_strings": ["input", "string", "output"],
    "segment_intersect": ["x", "y", "output"],
    "graham_scan": ["x", "y", "output"],
    "jarvis_march": ["x", "y", "output"],
    "bridges": ["input", "output"]
}
tasks = [
    "insertion_sort",
    "bubble_sort",
    "heap_sort",
    "quick_sort",
    "minimum",
    "binary_search",
    "quick_select",
    "maximum_subarray",
    "activity_selection",
    "task_scheduling",
    "matrix_chain_mul",
    "longest_common_subseq",
    "opt_bst",
    "bfs",
    "dfs",
    "topological_sort",
    "articulation_points",
    "strongly_connected_comps",
    "kruskal",
    "prim",
    "bellman_ford",
    "dijkstras",
    "floyd_warshall",
    "DAG_sp",
    "naive_strings",
    "kmp_strings",
    "segment_intersect",
    "graham_scan",
    "jarvis_march",
    "bridges"
]